name: gradle-setup
description: Setup Java and Gradle
runs:
  using: "composite"
  steps:
    - name: Make gradlew executable
      run: chmod +x gradlew
      shell: bash

    - name: Setup Java (v21 LTS)
      uses: actions/setup-java@v4.0.0
      with:
        java-version: "21"
        distribution: "temurin"

    - name: Setup Gradle (v9.1.0)
      uses: gradle/actions/setup-gradle@v4
